### ISSUE TITLE
部署到vercel 上报错

### ISSUE THREAD

**Issue by jugjhg** [langgenius/webapp-text-generator#13]
输入问题，点击**运行**之后，右侧不会显示任何回答信息。

vercel报错信息如下：
error - TypeError: This ReadableStream did not return bytes.
    at consumeUint8ArrayReadableStream (/var/task/node_modules/next/dist/compiled/edge-runtime/index.js:1:13979)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (/var/task/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:128:34)
    at async AppRouteRouteHandler.handle (/var/task/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:415:13)
    at async RouteHandlerManager.handle (/var/task/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:16:24)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:744:32)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/var/task/node_modules/next/dist/server/base-server.js:931:28)
    at async /var/task/node_modules/next/dist/server/response-cache/index.js:83:36

**Comment by iamjoel** [comment]
Can't reproduced. Can you provide more info?
