### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by LightGao-Hub** [langgenius/webapp-text-generator#18]
webapp-text-generator/app/api/parameters/route.ts Missing exception capture

**Comment by LightGao-Hub** [comment]
Causing Docker build failure, with exception logs as follows:
``` bash 
Error occurred prerendering page "/api/parameters". Read more: https://nextjs.org/docs/messages/prerender-error

[2024-04-15T12:23:36.268Z] Error: connect ECONNREFUSED ::1:80

[2024-04-15T12:23:36.268Z]     at AxiosError.from (/app/.next/server/chunks/35.js:3687:16)

[2024-04-15T12:23:36.268Z]     at RedirectableRequest.handleRequestError (/app/.next/server/chunks/35.js:5515:31)

[2024-04-15T12:23:36.268Z]     at RedirectableRequest.emit (node:events:513:28)

[2024-04-15T12:23:36.268Z]     at eventHandlers.<computed> (/app/.next/server/chunks/35.js:1364:28)

[2024-04-15T12:23:36.268Z]     at ClientRequest.emit (node:events:513:28)

[2024-04-15T12:23:36.268Z]     at Socket.socketErrorListener (node:_http_client:495:9)

[2024-04-15T12:23:36.268Z]     at Socket.emit (node:events:513:28)

[2024-04-15T12:23:36.268Z]     at emitErrorNT (node:internal/streams/destroy:151:8)

[2024-04-15T12:23:36.268Z]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)

[2024-04-15T12:23:36.268Z]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

[2024-04-15T12:23:36.268Z]     at Axios.request (/app/.next/server/chunks/35.js:6141:49)

[2024-04-15T12:23:36.268Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

[2024-04-15T12:23:36.268Z]     at async CompletionClient.sendRequest (/app/.next/server/chunks/35.js:6627:24)

[2024-04-15T12:23:36.268Z]     at async GET (/app/.next/server/app/api/parameters/route.js:148:23)

[2024-04-15T12:23:36.269Z]     at async AppRouteRouteHandler.execute (/app/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:330:26)

[2024-04-15T12:23:36.269Z]     at async AppRouteRouteHandler.handle (/app/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:410:30)

[2024-04-15T12:23:36.269Z]     at async /app/node_modules/next/dist/export/worker.js:236:42

[2024-04-15T12:23:36.269Z]     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)

[2024-04-15T12:23:36.269Z] info  - Generating static pages (3/7)

[2024-04-15T12:23:36.269Z] info  - Generating static pages (5/7)

[2024-04-15T12:23:36.269Z] info  - Generating static pages (7/7)
```
